- name: Configurar el servidor de produccion
  hosts: server-nodo-trabajo2
  gather_facts: no

  vars:
    service_account_file: ~/credentials.json
    project: practica3-sa
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
  - name: create a cluster
    google.cloud.gcp_container_cluster:
      name: cluster-grupo14 
      initial_node_count: 2
      master_auth:
        username: cluster_admin
        password: Guatemala_grupo14_2020
      node_config:
        machine_type: g1-small
        disk_size_gb: 30
      location: us-west3-a
      project: practica3-sa
      auth_kind: serviceaccount
      service_account_file: "{{service_account_file}}"
      state: present
    register: cluster 

  - name: Create a node pool to our microservices
    google.cloud.gcp_container_node_pool:
      name: my-pool
      initial_node_count: 2
      cluster: "{{ cluster }}"
      location: us-west3-a
      project: practica3-sa
      auth_kind: serviceaccount
      service_account_file: "{{ service_account_file}}"
      state: present

