- name: Configurar el servidor de produccion
  hosts: "servidor-nodo-trabajo2"
  gather_facts: no

  vars:
    service_account_file: ~/credentials.json
    project: practica3-sa
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    #Micro servicio usuario
    - name: kubectl delete deployment 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl delete deployment microservicio-usuario 

    - name: kubectl create deployment
      command: ~/despliegue/google-cloud-sdk/bin/kubectl create deployment microservicio-usuario --image=gcr.io/practica3-sa/microservicio-usuario-image:latest
    

    #Micro servicio producto
    - name: kubectl delete deployment 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl delete deployment microservicio-producto

    - name: kubectl create deployment
      command: ~/despliegue/google-cloud-sdk/bin/kubectl create deployment microservicio-producto --image=gcr.io/practica3-sa/microservicio-producto-image:latest
  
      
    #Micro servicio carrito
    - name: kubectl delete deployment 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl delete deployment microservicio-carrito

    - name: kubectl create deployment
      command: ~/despliegue/google-cloud-sdk/bin/kubectl create deployment microservicio-carrito --image=gcr.io/practica3-sa/microservicio-carrito-image:latest
  

    #Micro servicio compra
    - name: kubectl delete deployment 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl delete deployment microservicio-compra

    - name: kubectl create deployment
      command: ~/despliegue/google-cloud-sdk/bin/kubectl create deployment microservicio-compra --image=gcr.io/practica3-sa/microservicio-compra-image:latest
  

    #Micro servicio subasta
    - name: kubectl delete deployment 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl delete deployment microservicio-subasta

    - name: kubectl create deployment
      command: ~/despliegue/google-cloud-sdk/bin/kubectl create deployment microservicio-subasta --image=gcr.io/practica3-sa/microservicio-subasta-image:latest
  
    - name: kubectl get services
      command: ~/despliegue/google-cloud-sdk/bin/kubectl get services

   



