- name: Configurar el servidor de produccion
  hosts: "servidor-nodo-trabajo2"
  gather_facts: no

  vars:
    service_account_file: ~/credentials.json
    project: practica3-sa
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    - name: kubectl delete deployment 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/app-grupo14 microservicio-usuario-image=gcr.io/practica3-sa/microservicio-usuario-image:latest
