- name: Configurar el servidor de produccion
  hosts: "servidor-nodo-trabajo2"
  gather_facts: no

  vars:
    service_account_file: ~/credentials.json
    project: practica3-sa
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
    - name: kubectl update usuario
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/microservicio-usuario microservicio-usuario-image=gcr.io/practica3-sa/microservicio-usuario-image:latest

    - name: kubectl update producto 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/microservicio-producto microservicio-producto-image=gcr.io/practica3-sa/microservicio-producto-image:latest

    - name: kubectl update carrito 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/microservicio-carrito microservicio-carrito-image=gcr.io/practica3-sa/microservicio-carrito-image:latest

    - name: kubectl update compra 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/microservicio-compra microservicio-compra-image=gcr.io/practica3-sa/microservicio-compra-image:latest

    - name: kubectl update subasta 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/microservicio-subasta microservicio-subasta-image=gcr.io/practica3-sa/microservicio-subasta-image:latest

    - name: kubectl update esb 
      command: ~/despliegue/google-cloud-sdk/bin/kubectl set image deployment/esb-deploy imagen-esb-container=gcr.io/practica3-sa/imagen-esb-container:latest      


#grupo14-sa-2020